name: xmake check builds

on:
  workflow_call:

permissions:
  contents: read

jobs:
  xmake-check-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [alpine, ubuntu]
    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Prepare Docker image
        uses: docker/build-push-action@v7
        with:
          context: ci/
          file: ci/Dockerfile.${{ matrix.variant }}-xmake
          target: full
          load: true
          tags: tyghbn:post-merge-${{ matrix.variant }}-${{ github.sha }}
          cache-from: type=gha,scope=post-merge
          cache-to: type=gha,mode=max,scope=post-merge

      - name: Test building
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            --workdir /workspace \
            --entrypoint /bin/sh \
            tyghbn:post-merge-${{ matrix.variant }}-${{ github.sha }} \
            -c "xmake check-builds"
